### ISSUE TITLE
module :ssl is not available on nerves device

### ISSUE THREAD

**Issue by dkarter** [mobileoverlord/phoenix_channel_client#13]
Hi Justin, 

I am trying to get a simple example project running that shows Nerves developers how to remotely turn on an LED via websockets and using this library. I'm hoping this will be a good piece of documentation when I'm done + maybe  a blog post, time permitting.

My experience has been not very straight forward so far. I would love your help if and when you have the time :)

Also if this code looks familiar it is because I'm basing it on something you wrote for NervesHubClient.

Currently I'm running into an error when trying to run the following:

```elixir
defmodule RemoteLed.Client do
  alias RemoteLed.{LedSocket, ControlChannel}

  def connect do
    {:ok, _socket} = LedSocket.start_link()
    {:ok, _channel} = ControlChannel.start_link(socket: LedSocket, topic: "led:lobby")

    ControlChannel.join()
  end
end
```

With this config:

```elixir
config :remote_led, RemoteLed.LedSocket,
  url: "ws://ghost.local/socket/websocket",
  serializer: Jason
```

This is the error I'm getting:

```
iex(1)> RemoteLed.Client.connect
** (EXIT from #PID<0.444.0>) shell process exited with reason: an exception was raised
:
    ** (UndefinedFunctionError) function :ssl.start/0 is undefined (module :ssl is not
 available)
        :ssl.start()
        (phoenix_channel_client) lib/phoenix_channel_client/socket.ex:67: PhoenixChann
elClient.Socket.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Full code available here: https://github.com/dkarter/remote_led

Quesions:

1. How do I get :ssl to work on the rpi0 Nerves device?
2. Why is it even trying to use SSL to begin with when my configuration URL starts with `ws://` and not `wss://`?

Thanks,
Dorian

**Comment by mobileoverlord** [comment]
You could try adding `:ssl` to your list of `extra_applications`

**Comment by dkarter** [comment]
That works, thank you! :)
