### ISSUE TITLE
There does not seem to be a way to pass initial parameters

### ISSUE THREAD

**Issue by ashneyderman** [mobileoverlord/phoenix_channel_client#4]
Phoenix.js lib allows us to supply parameters on connect. Like so

`
let socket = new Socket("wss://localhost:4000/socket", {params: {authorization}})
`

I do not see an obvious way to achieve this with the current state of the lib. Is this a missing feature or my misunderstanding?

**Comment by mobileoverlord** [comment]
I believe you are correct. I am going to be making another pass through this and I can see about adding it in.

**Comment by mobileoverlord** [comment]
This feature is in master
